Repository komarichyn/time-management, pull requests merged in 2021-06, with the labels that each got.

#53 console/UI
  src/main/java/com/jc/tm/database/dao/TaskDaoImpl.java
  src/main/java/com/jc/tm/service/TaskServiceImpl.java
  src/main/java/com/jc/tm/ui/TaskConsole.java
  src/main/java/com/jc/tm/ui/subMenu/TaskSubMenu.java
Labels: bug

#54 Move to SpringFramework
  pom.xml
  src/main/java/com/jc/tm/Main.java
  src/main/resources/simplelogger.properties
Labels: feature, springframework

#59 move to JPA
  pom.xml
  src/main/java/com/jc/tm/Main.java
  src/main/java/com/jc/tm/database/dao/BaseDao.java
  src/main/java/com/jc/tm/database/dao/CommentDao.java
  src/main/java/com/jc/tm/database/dao/CommentDaoImpl.java
  src/main/java/com/jc/tm/database/dao/TaskDao.java
  src/main/java/com/jc/tm/database/dao/TaskDaoImpl.java
  src/main/java/com/jc/tm/database/entity/Comment.java
  src/main/java/com/jc/tm/db/Status.java
  src/main/java/com/jc/tm/db/dao/jpa/BaseDao.java
  src/main/java/com/jc/tm/db/dao/jpa/CommentDao.java
  src/main/java/com/jc/tm/db/dao/jpa/TaskDao.java
  src/main/java/com/jc/tm/db/entity/Comment.java
  src/main/java/com/jc/tm/db/entity/Task.java
  src/main/java/com/jc/tm/helper/DatabaseHelper.java
  src/main/java/com/jc/tm/helper/LoadPropertiesHelper.java
  src/main/java/com/jc/tm/service/ITaskService.java
  src/main/java/com/jc/tm/service/TaskServiceImpl.java
  src/main/java/com/jc/tm/ui/TaskConsole.java
  src/main/java/com/jc/tm/ui/subMenu/CommentSubMenu.java
  src/main/java/com/jc/tm/ui/subMenu/TaskSubMenu.java
  src/main/java/com/jc/tm/userInterface/CommentConsoleMenu.java
  src/main/java/com/jc/tm/userInterface/ConsoleApplication.java
  src/main/java/com/jc/tm/userInterface/TaskConsoleMenu.java
  src/main/resources/application.properties
  src/test/java/com/jc/tm/database/dao/TaskDaoImplTest.java
  src/test/java/com/jc/tm/db/ContextTest.java
  src/test/java/com/jc/tm/db/DbConfig.java
  src/test/resources/application.properties
Labels: database, feature, mysql, springframework
