Repository komarichyn/time-management, pull requests merged in 2021-05, with the labels that each got.

#24 configuration for supporting version of database
  docker-compose.yml
  pom.xml
  src/main/resources/flyway.conf
Labels: database

#38 configuration flyway was finished
  .gitignore
  conf/local-variables.env
  docker-compose.yml
  pom.xml
  src/main/java/com/jc/tm/Main.java
  src/main/java/com/jc/tm/database/dao/CommentDaoImpl.java
  src/main/java/com/jc/tm/database/dao/Jdbc.java
  src/main/java/com/jc/tm/database/dao/TaskDaoImpl.java
  src/main/java/com/jc/tm/helper/DatabaseHelper.java
  src/main/java/com/jc/tm/helper/LoadPropertiesHelper.java
  src/main/resources/application.properties
  src/main/resources/db/migration/V1_0__Init_database.sql
  src/main/resources/flyway.conf
Labels: database, mysql, wontfix

#43 Task.java added annotation @Data, also added dueDate variable and fix…
  src/main/java/com/jc/tm/database/dao/TaskDaoImpl.java
  src/main/java/com/jc/tm/database/entity/Task.java
  src/main/java/com/jc/tm/service/ITaskService.java
  src/main/java/com/jc/tm/service/TaskServiceImpl.java
Labels: bug
